services:
  content-service:
    build: ./backend/content-service
    ports:
      - "8080:8080"
    env_file:
      - .env  # Loads secrets like DB_PASSWORD
    environment:
      SPRING_PROFILES_ACTIVE: dev # Forces the profile for this specific file
    depends_on:
      - mongodb

  frontend:
    # image: node:24-alpine # Use a real Node image instead of building the Nginx one
    # working_dir: /app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app # Bind mount your code for hot-reloading
      - /app/node_modules # Anonymous volume prevents host node_modules from overwriting container ones
    command: npm run dev -- --host 0.0.0.0 # Crucial for Vite/Docker accessibility

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: