spring:
  application:
    name: content-service
  mongodb:
    host: localhost
    port: 27017
    database: storydb
    username: admin
    password: password123
    authentication-database: admin

server:
  port: 8080