spring:
  application:
    name: ${SPRING_APPLICATION_NAME:content-service}
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI:mongodb://admin:password123@localhost:27017/storydb?authSource=admin}

server:
  port: ${SERVER_PORT:8080}

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
