spring:
  application:
    name: ${SPRING_APPLICATION_NAME:content-service}
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI:mongodb://admin:password123@localhost:27017/storydb?authSource=admin}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

server:
  port: ${SERVER_PORT:8080}
  # This tells Spring Boot: "Everything starts with /api"
  servlet:
    context-path: /api  

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

# Add custom info here
info:
  app:
    name: Story Platform
    description: Backend for content service
    version: 1.0.0      
